services:
  - type: web
    name: peers-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: networth_db
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
